import type { Metadata } from 'next'
import './globals.css'

import { getServerSession } from 'next-auth';
// import { authOptions } from 'app/auth';
import { Navbar } from './components/navbar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <Navbar />
        <pre>{JSON.stringify(session)}</pre>
        {children}
      </body>
    </html>
  )
}
